### ISSUE TITLE
Incompatible with Laravel 5.2

### ISSUE THREAD

**Issue by PatrykTucki** [Ray-Cheng/laravel-socialite-api#1]
Hello,

Using the library with Laravel 5.2 throws the following error during php artisan optimize:

[ReflectionException]                                
  Class Illuminate\Foundation\Composer does not exist

**Comment by akulubala** [comment]
@PatrykTucki the error message suggest you don't have 'composer', make sure you have composer installed correctly

**Comment by aliasdoc** [comment]
Hi, in Laravel 5.2 
`
Illuminate\Foundation\Composer 
`
is replaced by 
`
Illuminate\Support\Composer
`

**Comment by akulubala** [comment]
@aliasdoc SocialiteProviders2.0 now support get user data by access  token. so for laravel5.2 you don't need this package anymore

blow is doc from SocialiteProviders2.0 : 

#### Retrieving User Details From Token

If you already have a valid access token for a user, you can retrieve their details using the `userFromToken` method:

```php
$user = Socialite::driver('github')->userFromToken($token);
```
